Models/Category.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Spice.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name="Category Name")]
        public string Name { get; set; }


    }
}

Models/ErrorViewModel.cs
using System;

namespace Spice.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            return View(await _db.Category.ToListAsync());
        }


        // GET - Create
        public IActionResult Create()
        {
            return View();
        }

        // POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if(ModelState.IsValid)
            {
                // if valid
                _db.Category.Add(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET - EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                // if valid
                _db.Update(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET - DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // GET - DELETE
        [HttpPost , ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var category = await _db.Category.FindAsync(id);

            if (category == null)
            {
                return View();
            }

            _db.Category.Remove(category);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET - DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
    }
}

Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Spice.Models;

namespace Spice.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/Admin/Views/Category/Create.cshtml
@model Category
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">
    Create Category
</h2>
<br />

<form method="post" asp-action="Create">
    <div class="border backgroundWhite">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control"/>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-5 offset-2" >
                <partial name="_CreateAddAndBackButton"/>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/Category/Delete.cshtml
@model Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">
    Delete Category
</h2>
<br />

<form method="post" asp-action="Delete">
    <div class="border backgroundWhite">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" readonly class="form-control"/>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-5 offset-2" >
                <partial name="_DeleteAndBackToListButton" model="Model.Id"/>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/Category/Details.cshtml
@model Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">
    Details Category
</h2>
<br />

<form method="post" asp-action="Details">
    <div class="border backgroundWhite">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" readonly class="form-control"/>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-5 offset-2" >
                <partial name="_DetailsAndBackToListButton" model="Model.Id"/>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/Category/Edit.cshtml
@model Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">
    Edit Category
</h2>
<br />

<form method="post" asp-action="Edit">
    <div class="border backgroundWhite">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control"/>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-5 offset-2" >
                <partial name="_EditAndBackToListButton" model="Model.Id"/>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/Category/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Category>
@{
    ViewData["Title"] = "Index";
    Layout = "/Views/Shared/_Layout.cshtml";
}

<br /> <br/>

<div class="border backgroundWhite">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">
                Category List
            </h2>
        </div>
        <div class="col-6 text-right">
            <partial name="_CreateButtonPartial"/>
        </div>
    </div>

    <br />

    <div>
        @if (Model.Count() > 0)
        {
        <table class="table table-triped border">
            <tr class="table-secondary">
                <th>
                    @Html.DisplayNameFor(m => m.Name)
                </th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.Name)
                    </td>
                    <td>
                        <partial name="_TableButtonPartial" model="item.Id" />
                    </td>
                </tr>
            }
        </table>
        } else
        {
            <p>
                No Category
            </p>
        }

    </div>
</div>

Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_CreateAddAndBackButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create"/>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control"> Back To List </a>
    </div>
</div>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info">
        <i class="fas fa-plus"></i> &nbsp; Create New
    </a>
</p>

Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete"/>
    </div>

    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">
            Back To List
        </a>
    </div>
</div>

Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" class="btn btn-info form-control" asp-route-id="@Model">
            Edit
        </a>
    </div>

    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">
            Back To List
        </a>
    </div>
</div>

Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update"/>
    </div>

    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">
            Back To List
        </a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                <a class="dropdown-item">Sub Category</a>
                                <a class="dropdown-item">MenuItem</a>
                                <a class="dropdown-item">Coupons</a>
                                <a class="dropdown-item">Users</a>
                            </div>

                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40">
        <div class="container">
            &copy; 2019 - Spice
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>